services:
  terraria:
    image: beardedio/terraria:tshock-5.2.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:7777"
    environment:
      - world=${WORLD_NAME}
    volumes:
      - ./config:/config
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
